version: '3.8'

services:
  postgres:
    
    image: pgvector/pgvector:pg17
    container_name: pgvector-db
    environment:
      POSTGRES_DB: face_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
